version: '3.8'
services:
  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
    networks:
      - app-network

  react_client:
    build:
      context: ./react_client
      dockerfile: Dockerfile
    ports:
      - "19006:19006"
    environment:
      - NODE_ENV=development
    depends_on:
      - flask_server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Alle containers stoppen:
# docker stop $(docker ps -a -q)     
# Containers verwijderen:
# docker rm $(docker ps -a -q)
# Om alle images te verwijderen:
# docker rmi $(docker images -q)


# Gebruik deze commando om image en container te runnen: 
# docker-compose up --build -d

# Als dit klaar is dan kan je de applicatie openen in de browser:
# http://localhost:19006

# Dit in browser of bruno check of je post kan ophalen:
# http://localhost:5000/posts/2

# Om de logs van de containers te bekijken:
# docker-compose logs -f